server:
  port: 9090

spring:
  kafka:
    bootstrap-servers: kafka-0:9092,kafka-1:9092,kafka-2:9092

    # Streams settings
    streams:
      application-id: message-processor
      properties:
        request.timeout.ms: 60000

    # Producer settings
    producer:
      acks: all
      retries: 3

    # Consumer settings
    consumer:
      auto-offset-reset: earliest
      group-id: message-processor-id
      properties:
        session.timeout.ms: 30000
        heartbeat.interval.ms: 10000