server.port=9090
spring.application.name=kafka-project-sprint-2

# kafka
spring.kafka.streams.application-id=message-processor
spring.kafka.bootstrap-servers=kafka-0:9092,kafka-1:9092
spring.kafka.streams.properties[request.timeout.ms]=60000

# producer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3

# consumer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.group-id=message-processor-id
spring.kafka.consumer.properties[session.timeout.ms]=30000
spring.kafka.consumer.properties[heartbeat.interval.ms]=10000